# Generated by Django 6.0.1 on 2026-01-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abbrobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrobot_name', models.CharField(max_length=200, verbose_name='机器人名字')),
                ('abbrobot_number', models.CharField(max_length=200, verbose_name='机器人编号')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP地址')),
                ('real_product_number', models.BigIntegerField(default=0, verbose_name='实时数量')),
                ('working_state', models.IntegerField(choices=[(1, '运行'), (0, '停止'), (2, '故障')], default=0, verbose_name='工作状态')),
                ('cycle_time', models.FloatField(default=0, verbose_name='节拍时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
    ]
