# Generated by Django 6.0.1 on 2026-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbrobot',
            name='good_product_number',
            field=models.BigIntegerField(default=0, verbose_name='良品数量'),
        ),
    ]
