# Generated by Django 6.0.1 on 2026-01-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myline', '0002_abbrobot_good_product_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_history', models.BigIntegerField(default=0, verbose_name='运行数量')),
                ('good_number', models.BigIntegerField(default=0, verbose_name='良品数量')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('device_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myline.abbrobot')),
            ],
        ),
    ]
